{{- $name := include "file-loader.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "file-loader.fullname" . }}
  labels:
    {{- include "file-loader.labels" . | nindent 4 }}
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "file-loader.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- include "file-loader.image.properties" . | nindent 8 }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        env:
          {{- with .Values.azureBlobStorage }}
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
                secretKeyRef:            
                  name: {{ .connectionSecret.name }}
                  key: {{ .connectionSecret.key }} 
          - name: CONTAINER_NAME
            value: {{ .containerName }}
          {{- end }}
          - name: INSERT_TEST_DATA
            value: {{ .Values.insertTestData | quote }}
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}
          {{- if .Values.env.configmap -}}
          {{- range .Values.env.configmap }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $cfgname }}
                  key: {{ .key }}
          {{- end -}}
          {{- end }}
          {{- if .Values.env.secrets -}}
          {{- range .Values.env.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:            
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}            
          {{- end -}}
          {{- end }}
      restartPolicy: OnFailure